# Generated by Django 3.2.13 on 2022-05-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
